(function(){
 'use strict';
 const data=window.PATTERNS,main=document.getElementById('main');
 const search=window.PatternSearch.createSearch(data.entries,data.concepts);
 const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const cat=s=>data.categories.find(c=>c.slug===s);
 const categoryLink=s=>'#/category/'+s;
 const queryLink=(q,c='all',type='all')=>'#/search?'+new URLSearchParams({q,...(c==='all'?{}:{category:c}),...(type==='all'?{}:{type})});
 const patternLink=(e,q='',c='all',type='all')=>'#/pattern/'+e.slug+(q?'?'+new URLSearchParams({q,category:c,type}):'');
 const crumb=(parts)=>'<nav class="crumbs" aria-label="Breadcrumb">'+parts.map(p=>'<span>'+(p.href?`<a href="${escape(p.href)}">${escape(p.title)}</a>`:escape(p.title))+'</span>').join('')+'</nav>';
 const homeCrumb={title:'Categories',href:'#/'};
 const collectionLink=(c,q='',back='')=>'#/collection/'+c.slug+(q||back?'?'+new URLSearchParams({q,...(back?{back}:{})}):'');
 function form(query='',home=false){return `<form class="search-box" role="search"><label class="sr-only" for="pattern-query">Search writing patterns</label><input id="pattern-query" name="q" type="search" maxlength="300" placeholder="Describe a pattern or paste a phrase" value="${escape(query)}" autocomplete="off" aria-describedby="search-help"><button type="submit">Search</button></form><p id="search-help" class="search-hint">${home?'Try “says a lot but nothing” or “not X, it’s Y”.':'Search descriptions, examples, and related concepts. Search includes the full word and phrase library.'}</p>`;}
 function suggestions(){return '<div class="suggestions" aria-label="Search suggestions">'+['Not X, it’s Y','Therapy speak','Too many adjectives','Same sentence structure','Says a lot but nothing'].map(q=>`<a href="${escape(queryLink(q))}">${escape(q)}</a>`).join('')+'</div>';}
 const marked=(text,q)=>window.PatternSearch.segments(text,q).map(p=>p.match?'<mark>'+escape(p.text)+'</mark>':escape(p.text)).join('');
 function row(e,{q='',category='all',type='all',reason='',snippet=''}={}){return `<a class="pattern-row ${reason?'result':''}" href="${escape(patternLink(e,q,category,type))}"><span class="row-title">${reason?`<span class="result-meta">${escape(cat(e.category).title)}${e.kind?' · '+escape(e.kind):''} · ${escape(reason)}</span>`:e.kind?`<span class="result-meta">${escape(e.kind)}</span>`:''}${marked(e.title,q)}</span><span class="row-description">${marked(snippet||e.example,q)}</span><span class="row-action" aria-hidden="true">View</span></a>`;}
 function home(){return `<div class="home-heading"><section class="intro"><h1>Categories</h1><p>Browse by category.</p></section><div class="home-search">${form('',true)}</div></div><p class="site-intro">This site is a compilation of many popular 'AI writing' tells. Also known as 'AI Slop.'</p><p class="library-intro"><a href="#/phrases">Browse words and phrases</a> — full inventories and additional forms.</p><section class="category-list" aria-label="Pattern categories">${data.categories.map(c=>`<a class="category-row" href="${categoryLink(c.slug)}"><span class="row-title">${escape(c.title)}</span><span class="row-description">${escape(c.description)}</span><span class="row-action" aria-hidden="true">View</span></a>`).join('')}</section>`;}
 function categoryEntries(slug){const entries=data.entries.filter(e=>e.category===slug);if(slug!=='language')return entries;const order=['its-not-x-its-y','repeated-stock-vocabulary','avoiding-is-and-has','forced-groups-of-three'];return [...order.map(s=>entries.find(e=>e.slug===s)).filter(Boolean),...entries.filter(e=>!order.includes(e.slug))];}
 function categoryPage(c){const entries=categoryEntries(c.slug); return `${crumb([homeCrumb,{title:c.title}])}<section class="intro"><h1>${escape(c.title)}</h1><p>${escape(c.description)}.</p></section>${c.slug==='context'?'<p class="notice">These entries need context. The items labeled “Unreliable indicator” should not be used as evidence of AI authorship.</p>':c.slug==='historical'?'<p class="notice">These observations concern earlier models and writing habits. They are not reliable tests of current AI use.</p>':''}<div class="pattern-list">${entries.map(e=>row(e)).join('')}</div><a class="back-link" href="#/">All categories</a>`;}
 function highlighted(example){const fragments=['This is not','It is a','not just','not only','it is','Additionally','underscores','pivotal','vibrant','clarity, confidence, and connection','No framework. No playbook. No magic.','Let that sink in','You already know','You are not alone'];const re=new RegExp('('+fragments.map(s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|')+')','gi');return example.split(re).map((part,i)=>i%2?'<mark>'+escape(part)+'</mark>':escape(part)).join('');}
 function detail(e,params){const c=cat(e.category),siblings=categoryEntries(e.category),i=siblings.indexOf(e);const related=data.entries.filter(p=>p!==e&&e.concepts.some(x=>p.concepts.includes(x))).slice(0,3);const q=params.get('q')||'',scope=params.get('category')||'all';return `<article class="detail">${crumb([homeCrumb,{title:c.title,href:categoryLink(c.slug)},{title:e.title}])}${q?`<div class="search-again"><a href="${escape(queryLink(q,scope,params.get('type')||'all'))}">Back to search results</a></div>`:''}<section class="intro">${e.kind?`<span class="badge">${escape(e.kind)}</span>`:''}<h1>${escape(e.title)}</h1><p>${escape(e.description)}</p></section><section class="example" aria-labelledby="example-label"><h2 class="eyebrow" id="example-label">Example</h2><blockquote>${highlighted(e.example)}</blockquote><p class="guidance">${escape(e.guidance)}</p><p class="small-note">Illustrative example.</p></section>${e.additionalExamples?.length?`<section class="additional-examples" aria-labelledby="additional-label"><h2 class="eyebrow" id="additional-label">More examples and related forms</h2>${e.additionalExamples.filter(v=>v.example!==e.example).map(v=>`<div class="variant"><h3>${escape(v.label)}</h3><p>${escape(v.example)}</p></div>`).join('')}</section>`:''}${e.supplemental?.length?`<section class="additional-examples"><h2 class="eyebrow">Additional forms</h2>${e.supplemental.map(s=>`<div class="variant"><h3>${escape(s.title)}</h3>${s.paragraphs.map(p=>`<p>${escape(p)}</p>`).join('')}</div>`).join('')}</section>`:''}${e.collections?.length?`<section class="related"><h2 class="eyebrow">Words and phrases</h2><div class="related-links">${e.collections.map(id=>data.library.find(c=>c.slug===id)).map(c=>`<a href="${collectionLink(c)}">${escape(c.title)}</a>`).join('')}</div></section>`:''}${related.length?`<section class="related"><h2 class="eyebrow">Related patterns</h2><div class="related-links">${related.map(p=>`<a href="${patternLink(p)}">${escape(p.title)}</a>`).join('')}</div></section>`:''}<p class="context-note">${escape(e.limit)}</p><nav class="detail-nav" aria-label="Pattern navigation">${i>0?`<a href="${patternLink(siblings[i-1])}" rel="prev">Previous: ${escape(siblings[i-1].title)}</a>`:`<a href="${categoryLink(c.slug)}">All ${escape(c.title.toLowerCase())} patterns</a>`}${i<siblings.length-1?`<a href="${patternLink(siblings[i+1])}" rel="next">Next: ${escape(siblings[i+1].title)}</a>`:`<a href="${categoryLink(c.slug)}">Back to ${escape(c.title.toLowerCase())}</a>`}</nav></article>`;}
 function searchPage(params){const q=(params.get('q')||'').slice(0,300),scope=cat(params.get('category'))?params.get('category'):'all';return `<section class="search-page">${crumb([homeCrumb,{title:'Search'}])}<section class="intro"><h1>Find a pattern</h1><p>Use your own words, or a phrase you’ve noticed.</p></section>${form(q)}<div class="filters"><label for="category-filter">Category <select id="category-filter" aria-label="Category"><option value="all">All categories</option>${data.categories.map(c=>`<option value="${c.slug}" ${scope===c.slug?'selected':''}>${escape(c.title)}</option>`).join('')}</select></label><label for="type-filter">Show <select id="type-filter" aria-label="Result type">${[['all','Everything'],['patterns','Patterns'],['phrases','Phrases & forms'],['vocabulary','Vocabulary']].map(([value,label])=>`<option value="${value}" ${params.get('type')===value?'selected':''}>${label}</option>`).join('')}</select></label><span id="result-count" role="status" aria-live="polite"></span></div><div id="search-results"></div></section>`;}
 function libraryRows(results,q,scope,type){return results.map(r=>{const best=r.matches[0];const why=best?(best.score===100?'Exact term':best.score===80?'Phrase match':'Related words or spelling'):'Collection title match';return `<a class="pattern-row result" href="${escape(collectionLink(r.collection,q,queryLink(q,scope,type)))}"><span class="row-title"><span class="result-meta">${escape(r.collection.group)} · ${why}</span>${marked(r.collection.title,q)}</span><span class="row-description">${r.matches.slice(0,3).map(m=>marked(window.PatternSearch.excerpt(m.text,q,200),q)).join(' · ')||'Browse the collection'}${r.matches.length>3?` · ${r.matches.length-3} more`:''}</span><span class="row-action" aria-hidden="true">View</span></a>`;}).join('');}
 function updateResults(){
  const input=document.getElementById('pattern-query'),filter=document.getElementById('category-filter');if(!filter)return;
  const q=input.value.trim().slice(0,300),scope=filter.value,type=document.getElementById('type-filter').value;
  const results=type==='all'||type==='patterns'?search(q,scope):[];
  const libraries=type==='patterns'?[]:window.PatternSearch.searchLibrary(data.library.filter(c=>(type==='all'||(type==='vocabulary'?c.group==='Vocabulary lists':c.group!=='Vocabulary lists'))&&(scope==='all'||c.related.some(slug=>data.entries.some(e=>e.slug===slug&&e.category===scope)))),q);
  document.getElementById('result-count').textContent=q?`${results.length} ${results.length===1?'pattern':'patterns'} · ${libraries.length} ${libraries.length===1?'collection':'collections'}`:'';
  const libraryHTML=libraries.length?`<h2 class="results-heading">Words and phrases</h2><div class="pattern-list">${libraryRows(libraries,q,scope,type)}</div>`:'';
  const patternHTML=results.length?`<h2 class="results-heading">Patterns</h2><div class="pattern-list">${results.map(r=>row(r.entry,{q,category:scope,type,...window.PatternSearch.explain(r,q,data.concepts)})).join('')}</div>`:'';
  const alternatives=q?window.PatternSearch.suggestQueries(q,data.entries,data.concepts,data.library):[];
  const suggestionsHTML=alternatives.length?`<div class="query-alternatives"><p>Try another search</p><div class="suggestions">${alternatives.map(term=>`<a href="${escape(queryLink(term,scope,type))}">${escape(term)}</a>`).join('')}</div></div>`:'';
  const clearFilters=scope!=='all'||type!=='all'?`<a class="clear-filters" href="${escape(queryLink(q))}">Search all categories and content types</a>`:'';
  document.getElementById('search-results').innerHTML=!q?`<div class="empty"><h2>Start with something you’ve noticed.</h2><p>A description works as well as a name.</p>${suggestions()}</div>`:!results.length&&!libraries.length?`<div class="empty"><h2>No matches${scope!=='all'||type!=='all'?' with these filters':''}</h2><p>Try fewer words or a different description.</p>${clearFilters}${suggestionsHTML}<a href="#/phrases">Browse words and phrases</a></div>`:clearFilters+suggestionsHTML+(libraries.some(r=>r.matches.some(m=>m.score===100))?libraryHTML+patternHTML:patternHTML+libraryHTML);
  history.replaceState(null,'',queryLink(q,scope,type));
 }
 function libraryPage(){return `${crumb([homeCrumb,{title:'Words and phrases'}])}<section class="intro"><h1>Words and phrases</h1><p>Browse full phrase collections, vocabulary lists and additional forms.</p></section>${form()}${['Phrase collections','Additional forms','Vocabulary lists'].map(group=>`<section><h2 class="results-heading">${group}</h2><div class="pattern-list">${data.library.filter(c=>c.group===group).map(c=>`<a class="pattern-row" href="${collectionLink(c)}"><span class="row-title">${escape(c.title)}</span><span class="row-description">${c.terms.length?`${c.terms.length.toLocaleString()} words and phrases`:escape(c.paragraphs[0].slice(0,145))+'…'}</span><span class="row-action" aria-hidden="true">View</span></a>`).join('')}</div></section>`).join('')}`;}
 function collectionPage(c,params){const q=(params.get('q')||'').slice(0,300),back=params.get('back')||'';return `${back.startsWith('#/search?')?`<div class="search-again"><a href="${escape(back)}">Back to search results</a></div>`:''}${crumb([homeCrumb,{title:'Words and phrases',href:'#/phrases'},{title:c.title}])}<section class="intro"><h1>${escape(c.title)}</h1>${c.note?`<p>${escape(c.note)}</p>`:''}</section><div class="collection-controls"><label for="collection-query">Find in this collection</label><input id="collection-query" type="search" maxlength="300" value="${escape(q)}" placeholder="Enter a word or phrase"><button id="clear-collection" type="button">Show all</button><span id="collection-count" role="status" aria-live="polite"></span></div><div id="collection-content"></div><section class="related"><h2 class="eyebrow">Related patterns</h2><div class="related-links">${c.related.map(slug=>data.entries.find(e=>e.slug===slug)).map(e=>`<a href="${patternLink(e)}">${escape(e.title)}</a>`).join('')}</div><a class="back-link" href="#/phrases">All words and phrases</a>`;}
 function updateCollection(c){const q=document.getElementById('collection-query').value.trim();const matches=q?window.PatternSearch.searchLibrary([c],q)[0]?.matches||[]:(c.terms.length?c.terms:c.paragraphs).map(text=>({text}));document.getElementById('collection-count').textContent=`${matches.length} ${c.terms.length?(matches.length===1?'term':'terms'):(matches.length===1?'passage':'passages')}${q?' matching':''}`;document.getElementById('collection-content').innerHTML=matches.length?(c.terms.length?`<ul class="term-list">${matches.map(m=>`<li>${marked(m.text,q)}</li>`).join('')}</ul>`:`<div class="prose collection-prose">${matches.map(m=>`<p>${marked(m.text,q)}</p>`).join('')}</div>`):'<p class="empty">No matches in this collection. Select Show all to read the full list.</p>';const back=new URLSearchParams(location.hash.split('?').slice(1).join('?')).get('back')||'';history.replaceState(null,'',collectionLink(c,q,back));}
 function sources(){return `${crumb([homeCrumb,{title:'Sources'}])}<section class="intro"><h1>Sources</h1></section><section aria-label="Source list">${data.sources.map(s=>`<article class="source-row"><h2><a href="${escape(s.url)}" target="_blank" rel="noopener noreferrer">${escape(s.title)}</a></h2></article>`).join('')}</section>`;}
 function about(){return `${crumb([homeCrumb,{title:'About'}])}<section class="intro"><h1>About</h1></section><div class="prose"><p>This site is a compilation of many popular 'AI writing' tells. Also known as 'AI Slop.'</p><p>This site is for educational purposes only. Seeing one of these writing techniques in someone's writing is not a guarantee that it was AI generated. AI did learn to write from humans, after all.</p><h2>Search</h2><p>Use the search feature to look for a specific type of AI writing, or browse the site by category.</p><h2>Sources</h2><p>The sources section includes links to primary sources and repos for all the AI writing tells shown on this site. I thank them for their service.</p><p>This site was last updated in October 2026.</p></div>`;}
 let timer;
 function render(){clearTimeout(timer);let path,params;try{const [route,query='']=(location.hash.slice(1)||'/').split('?');path=decodeURIComponent(route);params=new URLSearchParams(query);}catch{path='/invalid';params=new URLSearchParams();}
 if(path==='/checker'){history.replaceState(null,'','#/');path='/';params=new URLSearchParams();}
 let title='Categories',html;
 if(path==='/')html=home();else if(path==='/search'){html=searchPage(params);title='Search';}else if(path==='/phrases'){html=libraryPage();title='Words and phrases';}else if(path.startsWith('/collection/')&&data.library.find(c=>c.slug===path.slice(12))){const c=data.library.find(c=>c.slug===path.slice(12));html=collectionPage(c,params);title=c.title;}else if(path==='/sources'){html=sources();title='Sources';}else if(path==='/about'){html=about();title='About';}else if(path.startsWith('/category/')&&cat(path.slice(10))){const c=cat(path.slice(10));html=categoryPage(c);title=c.title;}else if(path.startsWith('/pattern/')&&data.entries.find(e=>e.slug===path.slice(9))){const e=data.entries.find(e=>e.slug===path.slice(9));html=detail(e,params);title=e.title;}else{title='Page not found';html='<section class="intro"><h1>Page not found</h1><p>This link does not match a pattern in the reference.</p></section><a href="#/">Browse categories</a>';}
 main.innerHTML=html;document.title=title+' | AI Slop Patterns';document.querySelectorAll('.masthead nav a').forEach(a=>{if(a.getAttribute('href')==='#'+path)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
 const f=main.querySelector('form');if(f)f.addEventListener('submit',event=>{event.preventDefault();const q=f.querySelector('input').value.trim().slice(0,300);if(path==='/search')updateResults();else location.hash=queryLink(q);});
 if(path==='/search'){updateResults();document.getElementById('pattern-query').addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(updateResults,120);});document.getElementById('category-filter').addEventListener('change',updateResults);document.getElementById('type-filter').addEventListener('change',updateResults);}
 if(path.startsWith('/collection/')&&document.getElementById('collection-query')){const c=data.library.find(c=>c.slug===path.slice(12));updateCollection(c);document.getElementById('collection-query').addEventListener('input',()=>updateCollection(c));document.getElementById('clear-collection').addEventListener('click',()=>{document.getElementById('collection-query').value='';updateCollection(c);});}
 window.scrollTo(0,0);main.focus({preventScroll:true});
 }
 document.querySelector('.skip').addEventListener('click',event=>{event.preventDefault();main.focus();main.scrollIntoView();});
 window.addEventListener('hashchange',render);render();
})();
