(function(){
 'use strict';
 const data=window.PATTERNS,main=document.getElementById('main');
 const search=window.PatternSearch.createSearch(data.entries,data.concepts);
 const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const cat=s=>data.categories.find(c=>c.slug===s);
 const categoryLink=s=>'#/category/'+s;
 const queryLink=(q,c='all')=>'#/search?'+new URLSearchParams({q,...(c==='all'?{}:{category:c})});
 const patternLink=(e,q='',c='all')=>'#/pattern/'+e.slug+(q?'?'+new URLSearchParams({q,category:c}):'');
 const crumb=(parts)=>'<nav class="crumbs" aria-label="Breadcrumb">'+parts.map(p=>'<span>'+(p.href?`<a href="${escape(p.href)}">${escape(p.title)}</a>`:escape(p.title))+'</span>').join('')+'</nav>';
 const homeCrumb={title:'Categories',href:'#/'};
 function form(query='',home=false){return `<form class="search-box" role="search"><label class="sr-only" for="pattern-query">Search writing patterns</label><input id="pattern-query" name="q" type="search" maxlength="300" placeholder="Describe a pattern or paste a phrase" value="${escape(query)}" autocomplete="off" aria-describedby="search-help"><button type="submit">Search</button></form><p id="search-help" class="search-hint">${home?'Try “says a lot but nothing” or “not X, it’s Y”.':'Search descriptions, examples, and related concepts. Your search stays in this browser.'}</p>`;}
 function suggestions(){return '<div class="suggestions" aria-label="Search suggestions">'+['Not X, it’s Y','Therapy speak','Too many adjectives','Same sentence structure','Says a lot but nothing'].map(q=>`<a href="${escape(queryLink(q))}">${escape(q)}</a>`).join('')+'</div>';}
 function row(e,{q='',category='all',reason=''}={}){return `<a class="pattern-row ${reason?'result':''}" href="${escape(patternLink(e,q,category))}"><span class="row-title">${reason?`<span class="result-meta">${escape(cat(e.category).title)}${e.kind?' · '+escape(e.kind):''} · ${escape(reason)}</span>`:e.kind?`<span class="result-meta">${escape(e.kind)}</span>`:''}${escape(e.title)}</span><span class="row-description">${escape(e.example)}</span><span class="row-action" aria-hidden="true">View</span></a>`;}
 function home(){return `<div class="home-heading"><section class="intro"><h1>Categories</h1><p>Browse by category.</p></section><div class="home-search">${form('',true)}</div></div><section class="category-list" aria-label="Pattern categories">${data.categories.map(c=>`<a class="category-row" href="${categoryLink(c.slug)}"><span class="row-title">${escape(c.title)}</span><span class="row-description">${escape(c.description)}</span><span class="row-action" aria-hidden="true">View</span></a>`).join('')}</section>`;}
 function categoryEntries(slug){const entries=data.entries.filter(e=>e.category===slug);if(slug!=='language')return entries;const order=['its-not-x-its-y','repeated-stock-vocabulary','avoiding-is-and-has','forced-groups-of-three'];return [...order.map(s=>entries.find(e=>e.slug===s)).filter(Boolean),...entries.filter(e=>!order.includes(e.slug))];}
 function categoryPage(c){const entries=categoryEntries(c.slug); return `${crumb([homeCrumb,{title:c.title}])}<section class="intro"><h1>${escape(c.title)}</h1><p>${escape(c.description)}.</p></section>${c.slug==='context'?'<p class="notice">These entries need context. The items labeled “Unreliable indicator” should not be used as evidence of AI authorship.</p>':c.slug==='historical'?'<p class="notice">These observations concern earlier models and writing habits. They are not reliable tests of current AI use.</p>':''}<div class="pattern-list">${entries.map(e=>row(e)).join('')}</div><a class="back-link" href="#/">All categories</a>`;}
 function highlighted(example){const fragments=['This is not','It is a','not just','not only','it is','Additionally','underscores','pivotal','vibrant','clarity, confidence, and connection','No framework. No playbook. No magic.','Let that sink in','You already know','You are not alone'];const re=new RegExp('('+fragments.map(s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|')+')','gi');return example.split(re).map((part,i)=>i%2?'<mark>'+escape(part)+'</mark>':escape(part)).join('');}
 function detail(e,params){const c=cat(e.category),siblings=categoryEntries(e.category),i=siblings.indexOf(e);const related=data.entries.filter(p=>p!==e&&e.concepts.some(x=>p.concepts.includes(x))).slice(0,3);const q=params.get('q')||'',scope=params.get('category')||'all';return `<article class="detail">${crumb([homeCrumb,{title:c.title,href:categoryLink(c.slug)},{title:e.title}])}${q?`<div class="search-again"><a href="${escape(queryLink(q,scope))}">Back to search results</a></div>`:''}<section class="intro">${e.kind?`<span class="badge">${escape(e.kind)}</span>`:''}<h1>${escape(e.title)}</h1><p>${escape(e.description)}</p></section><section class="example" aria-labelledby="example-label"><h2 class="eyebrow" id="example-label">Example</h2><blockquote>${highlighted(e.example)}</blockquote><p class="guidance">${escape(e.guidance)}</p><p class="small-note">Illustrative example.</p></section>${related.length?`<section class="related"><h2 class="eyebrow">Related patterns</h2><div class="related-links">${related.map(p=>`<a href="${patternLink(p)}">${escape(p.title)}</a>`).join('')}</div></section>`:''}<p class="context-note">${escape(e.limit)}</p><nav class="detail-nav" aria-label="Pattern navigation">${i>0?`<a href="${patternLink(siblings[i-1])}" rel="prev">Previous: ${escape(siblings[i-1].title)}</a>`:`<a href="${categoryLink(c.slug)}">All ${escape(c.title.toLowerCase())} patterns</a>`}${i<siblings.length-1?`<a href="${patternLink(siblings[i+1])}" rel="next">Next: ${escape(siblings[i+1].title)}</a>`:`<a href="${categoryLink(c.slug)}">Back to ${escape(c.title.toLowerCase())}</a>`}</nav></article>`;}
 function searchPage(params){const q=(params.get('q')||'').slice(0,300),scope=cat(params.get('category'))?params.get('category'):'all';return `<section class="search-page">${crumb([homeCrumb,{title:'Search'}])}<section class="intro"><h1>Find a pattern</h1><p>Use your own words, or a phrase you’ve noticed.</p></section>${form(q)}<div class="filters"><label for="category-filter">Category <select id="category-filter" aria-label="Category"><option value="all">All categories</option>${data.categories.map(c=>`<option value="${c.slug}" ${scope===c.slug?'selected':''}>${escape(c.title)}</option>`).join('')}</select></label><span id="result-count" role="status" aria-live="polite"></span></div><div id="search-results"></div></section>`;}
 function updateResults(){const input=document.getElementById('pattern-query'),filter=document.getElementById('category-filter');if(!filter)return;const q=input.value.trim().slice(0,300),scope=filter.value,results=search(q,scope);document.getElementById('result-count').textContent=q?`${results.length} ${results.length===1?'result':'results'}`:'';document.getElementById('search-results').innerHTML=!q?`<div class="empty"><h2>Start with something you’ve noticed.</h2><p>A description works as well as a name.</p>${suggestions()}</div>`:!results.length?`<div class="empty"><h2>No matching patterns</h2><p>Try a shorter phrase${scope!=='all'?' or choose All categories':''}. You can also browse the categories.</p>${suggestions()}<a href="#/">Browse all categories</a></div>`:`<div class="pattern-list">${results.map(r=>row(r.entry,{q,category:scope,reason:r.reason})).join('')}</div>`;history.replaceState(null,'',queryLink(q,scope));}
 function sources(){return `${crumb([homeCrumb,{title:'Sources'}])}<section class="intro"><h1>Sources</h1><p>The articles, research, and rule collections behind this reference.</p></section><div class="prose"><p>The catalog combines published observations with editorial guidance. Overlapping patterns have been grouped, and the examples were written for this reference. A source’s observation is not a validated authorship test.</p></div><div class="download-links"><a href="./downloads/ai-writing-signs-and-rules.md" download>Download the full reference</a><a href="./downloads/source-register.xlsx" download>Download the source register</a></div><section class="prose"><h2>Attribution and licensing</h2><p>The reference adapts work by <a href="https://en.wikipedia.org/wiki/Wikipedia:Signs_of_AI_writing" target="_blank" rel="noopener noreferrer">Wikipedia contributors</a> and <a href="https://github.com/ammil-industries/vale-signs-of-ai-writing" target="_blank" rel="noopener noreferrer">ammil-industries</a>. Adapted reference material is available under <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a>. Changes include regrouping, rewritten explanations, examples and editing advice. Other cited material retains its own terms. The application code is <a href="./LICENSE">MIT licensed</a>.</p><p><a href="https://en.wikipedia.org/w/index.php?title=Wikipedia:Signs_of_AI_writing&amp;action=history" target="_blank" rel="noopener noreferrer">Wikipedia contributor history</a> · <a href="./NOTICE.md">Full attribution notice</a></p><p class="small-note">Sources reviewed 2 October 2026. No endorsement by the cited authors or organizations is implied.</p></section><section aria-label="Source list">${data.sources.map(s=>`<article class="source-row"><h2><a href="${escape(s.url)}" target="_blank" rel="noopener noreferrer">${escape(s.title)}</a></h2><p>${escape(s.description)}</p><p class="source-limit">${escape(s.limit)}</p></article>`).join('')}</section>`;}
 function about(){return `${crumb([homeCrumb,{title:'About'}])}<section class="intro"><h1>About this reference</h1><p>A way to look closely at writing.</p></section><div class="prose"><p>Browse recurring patterns in phrasing, content and presentation. Each entry includes an example, editing guidance and a qualification. The collection is designed for discussion with clients and students.</p><h2>Use the context</h2><p>People use these constructions too. A phrase, punctuation mark or polished paragraph cannot establish who wrote a passage. Historical patterns and unreliable indicators are labeled separately.</p><p>The examples illustrate a construction; their claims and characters are not factual case studies. This site does not score documents or make authorship judgments.</p><h2>Search in your own words</h2><p>Search connects related expressions, checks examples and allows for common spelling differences. For example, “therapy speak” can find unnecessary reassurance, and “says a lot but nothing” can find information-poor generalities.</p><p>It uses a curated vocabulary and text matching. There is no language model, account or API key. Queries stay in your browser. No analytics, external fonts or search services are loaded. Unfamiliar descriptions may need a shorter query.</p><h2>Read further</h2><p>The <a href="#/sources">Sources section</a> includes the full reference, source register and attribution.</p></div>`;}
 let timer;
 function render(){clearTimeout(timer);let path,params;try{const [route,query='']=(location.hash.slice(1)||'/').split('?');path=decodeURIComponent(route);params=new URLSearchParams(query);}catch{path='/invalid';params=new URLSearchParams();}
 let title='Categories',html;
 if(path==='/')html=home();else if(path==='/search'){html=searchPage(params);title='Search';}else if(path==='/sources'){html=sources();title='Sources';}else if(path==='/about'){html=about();title='About';}else if(path.startsWith('/category/')&&cat(path.slice(10))){const c=cat(path.slice(10));html=categoryPage(c);title=c.title;}else if(path.startsWith('/pattern/')&&data.entries.find(e=>e.slug===path.slice(9))){const e=data.entries.find(e=>e.slug===path.slice(9));html=detail(e,params);title=e.title;}else{title='Page not found';html='<section class="intro"><h1>Page not found</h1><p>This link does not match a pattern in the reference.</p></section><a href="#/">Browse categories</a>';}
 main.innerHTML=html;document.title=title+' | AI Writing Patterns';document.querySelectorAll('.masthead nav a').forEach(a=>{if(a.getAttribute('href')==='#'+path)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
 const f=main.querySelector('form');if(f)f.addEventListener('submit',event=>{event.preventDefault();const q=f.querySelector('input').value.trim().slice(0,300);if(path==='/search')updateResults();else location.hash=queryLink(q);});
 if(path==='/search'){updateResults();document.getElementById('pattern-query').addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(updateResults,120);});document.getElementById('category-filter').addEventListener('change',updateResults);}
 window.scrollTo(0,0);main.focus({preventScroll:true});
 }
 document.querySelector('.skip').addEventListener('click',event=>{event.preventDefault();main.focus();main.scrollIntoView();});
 window.addEventListener('hashchange',render);render();
})();
